// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoIRWrskVbwzD-jnjsnRy7qUiYFnH2NQ',
    appId: '1:528884378593:web:3c1b6dae85c24c65b0c0a0',
    messagingSenderId: '528884378593',
    projectId: 'crestaurante-1f084',
    authDomain: 'crestaurante-1f084.firebaseapp.com',
    storageBucket: 'crestaurante-1f084.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAARWvpDZYZbLZS9YyKd3p5OrocXgHTxBI',
    appId: '1:528884378593:android:ae698535dfe840dcb0c0a0',
    messagingSenderId: '528884378593',
    projectId: 'crestaurante-1f084',
    storageBucket: 'crestaurante-1f084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDKVQjhGoghhATfD6_R9dDvNi4eM4j_Eo',
    appId: '1:528884378593:ios:67ce26ee7caaf715b0c0a0',
    messagingSenderId: '528884378593',
    projectId: 'crestaurante-1f084',
    storageBucket: 'crestaurante-1f084.appspot.com',
    iosBundleId: 'com.example.learning210c',
  );
}
